<?php
/**
 * @file
 * NNELS Stats module.
 */

/**
 * Implements hook_menu().
 */
function nnels_stats_menu() {
  $items = array();
  
	$items['admin/config/nnels_stats'] = array(
    'title' => 'Test NNELS Stats Entity Status',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'nnels_stats_test_entity',
    'type' => MENU_NORMAL_ITEM,
	);
	
	
  
  return $items;
}

/**
 * Implements hook_init().
 */
function nnels_stats_init() {
	//
	$ips = array('99.246.47.248', '70.26.15.139', '50.69.30.84');
	$ip = $_SERVER['REMOTE_ADDR'];
	$ref = nnels_stats_get_referrer();
  //printAndDie($ref);
	//if(in_array($ip, $ips)) _nnels_stats_tracker();
	 _nnels_stats_tracker();
}



 
/**
 * Implements hook_user_logout().
 */
function nnels_stats_user_logout($account) {

	dpm(__FUNCTION__);
  
}

/**
 * Implements hook_user_login().
 */
function nnels_stats_user_login(&$edit, $account) {
  global $user;
	dpm(__FUNCTION__);
	//if no login session, its likely because we're dealing w/ referring_url_type = 4
	if(empty($_SESSION['nnels_stats'])) {
		$orgid = nnels_stats_get_org_by_uid($account->uid);
		$ip = $_SERVER['REMOTE_ADDR'];
		//get the referring URL
  	$ref = nnels_stats_get_referrer();
		//referring url types: 1 = blank / direct; 2 = external (not partner); 3 = referring (partner); 4 = site?
		$referring_url_type = 4; //?? nnels_stats_get_url_type($ref); 
	  _nnels_stats_set_session($account, $orgid, $ref, $referring_url_type, $ip);
	}
	else {
		_nnels_stats_update_session($account);
	}	
}


/**
 * Implementation of hook_user_insert().
 */
function nnels_stats_user_insert(&$edit, $account, $category) {
	
	if(!empty($_SESSION['nnels_stats'])) {
		$arr = $_SESSION['nnels_stats'];
		if(!empty($arr['visitid']) ) {
			$arr['orgid'] = $_SESSION['calsauthen_target_organization']; //just to be certain we're getting the orgid
			$arr['new_user'] = 1;
			$arr['authen_result'] = 1;
			$arr['role'] = 1;
			//$arr['authen_success'] = 0;
			//$arr['authen_status'] = 1;
			//$arr['authen_failure_reason'] = 0;
			//_nnels_update_visit($arr, $success, $reason,
			_nnels_update_visit($arr, 1, 0, $account->uid);  
			unset($_SESSION['nnels_stats']);
			dpm(__FUNCTION__);
		}	
	
	}
	dpm(__FUNCTION__);
  
}

/**
 * Implements hook_calsauthen_login_result.
 *
 * @param bool $result
 *   TRUE if the login was successful, FALSE if not.
 * @param string $reason
 *   The reason that the user's login attempt failed. Should be on of
 *   1 (username unknown), 2 (bad password), 3 (invalid patron type),
 *   4 (blocked account). NULL for successful logins.
 */
function nnels_stats_calsauthen_login_result($result, $reason = NULL, $uid = NULL) {
  //dd($_SESSION['calsauthen_target_organization'], 'Org');
  //dd($_SESSION['calsauthen_target_driver'], 'Driver');
  
  if($_SESSION['nnels_stats']['orgid'] == 0) {
		$_SESSION['nnels_stats']['orgid'] = $_SESSION['calsauthen_target_organization'];
  	$_SESSION['nnels_stats']['target_orgid'] = $_SESSION['calsauthen_target_organization'];
  }
  if($uid > 0) {
		$orgid = nnels_stats_get_org_by_uid($uid);
		$_SESSION['nnels_stats']['orgid'] = $orgid;
  	$_SESSION['nnels_stats']['target_orgid'] = $orgid;
  
  }
	dpm(__FUNCTION__);


	$arr = isset($_SESSION['nnels_stats']) ? $_SESSION['nnels_stats'] : array();
	
	
  if ($result) {
    _nnels_update_visit($arr, 1, 0, $uid);
    unset($_SESSION['nnels_stats']); // clear session
  }
  else {
    dpm("Oops, failed login: $reason");
    //dd($reason, 'Reason');
    //$_SESSION['nnels_stats']
    
    
		_nnels_update_visit($arr, 0, $reason, $uid);
		reset_session_failed_login($arr, $uid);
    //unset($_SESSION['nnels_stats']); // clear session
  }


}


/**
 * Implements hook_views_api().
 */
function nnels_stats_views_api() {
    return array(
        'api' => 3,
        'path' => drupal_get_path('module', 'nnels_stats') . '/includes/views',
    );
}


/**
 * the main stats tracker
 *
 * @return
 *   tba
 * @todo
 *   lots to do here, like lots
 */
function _nnels_stats_tracker() {

  global $user;
  if( !in_array("patron", $user->roles) && !in_array("anonymous user", $user->roles) ) return;
	$ip = $_SERVER['REMOTE_ADDR'];
	//if($ip != '99.246.47.248') return;
	//does the session exist?  
  $session_exists = (isset($_SESSION['nnels_stats']) ) ? TRUE : FALSE;
  
  //get the referring URL
  $ref = nnels_stats_get_referrer();
	//referring url types: 1 = blank / direct; 2 = external (not partner); 3 = referring (partner); 4 = site?
	$referring_url_type = nnels_stats_get_url_type($ref); 
	

	drupal_set_message("ip = $ip");
	drupal_set_message("ref url type: $referring_url_type");

  if($user->uid > 0 && $session_exists === TRUE) {
    unset($_SESSION['nnels_stats']);
    $session_exists = FALSE;
  }
	//&& $session_exists === FALSE && $user->uid > 0
  if ($referring_url_type === 4 && $session_exists === FALSE) {
	  dpm("we don't track this");
		//unset($_SESSION['nnels_stats']);
    return;
  }
  
 
  if (isset($_SESSION['nnels_stats']['referring_url_type']) && $_SESSION['nnels_stats']['referring_url_type'] == 4) {
  	
    return;
  }
 
  //BLANK / BOOKMARKED URL
  if($referring_url_type == 1) {
   	//return;

  }
  //EXTERNAL URL / NOT PARTNER
  if($referring_url_type == 2) {
    
  }
  //EXTERNAL URL / PARTNER
  if($referring_url_type == 3) {
  }
  
  
  
	$orgid = 0;
	if(isset($_SESSION['calsauthen_target_organization'])) {
	  $orgid = $_SESSION['calsauthen_target_organization'];
	}
	//logged in user coming from other site
	if($user->uid > 0 && $referring_url_type < 4) {
	  $visitid = _nnels_stats_add_visit_loggedin($user, $ref, $referring_url_type, $ip);
		//return;
	}	
	//$session_exists === FALSE || referring URL is not site based 
  if($user->uid == 0 && (empty($_SESSION['nnels_stats']['visitid']) || $referring_url_type < 4) ) {
	  _nnels_stats_set_session($user, $orgid, $ref, $referring_url_type, $ip);
		$session_exists = TRUE;  
	 	$visitid = $_SESSION['nnels_stats']['visitid'];
  }
	//track pages visited on site before logging in. This is not yet implemented into the DB...
  if( isset($_SESSION['nnels_stats']) ) {
    $_SESSION['nnels_stats']['pages'][] = check_plain(request_uri()); //should use check_plain()?
   	dpm($_SESSION['nnels_stats']);
    //if($user->uid < 1) _nnels_add_visit($_SESSION['nnels_stats']);
  }  
	drupal_set_message(__METHOD__ . ": referring_url_type = $referring_url_type | REFERRING URL = " . $ref . " | UID = " . $user->uid . " | orgid = $orgid | session_exists = " . $session_exists . " | visitid = $visitid");
	dpm($_SESSION);  


}

function reset_session_failed_login($arr, $uid) {

	$arr['visitid'] = _nnels_add_visit($arr);
	$_SESSION['nnels_stats'] = $arr;
}

/**
 * Sets nnels_stats session
 *
 * @param array $arr
 *   
 */
function _nnels_stats_update_session($account) {
	
  if(!empty($account->field_organization)) $_SESSION['nnels_stats']['orgid'] = $account->field_organization['und'][0]['nid'];
}

/**
 * Adds a new row for returning users who are already logged in. No session is created.
 *
 * @param array $arr
 *   
 */
function _nnels_stats_add_visit_loggedin($acct, $ref, $referring_url_type, $ip) {
	$orgid = nnels_stats_get_org_by_uid($acct->uid);
	$arr = array(
	  'referrer' => $ref,
	  'new_user' => 0, //0=returning user, 1=new ... override this in hook_user_insert
	  'referring_url_type' => $referring_url_type,
	  'orgid' => $orgid,
	  'pages' => array(),
	  'authen_result' => 6,
	  'ip_address' => $ip,
	);
	_nnels_add_visit($arr);

}

/**
 * Sets nnels_stats session
 *
 * @param array $arr
 *   
 */
function _nnels_stats_set_session($acct, $orgid, $ref, $referring_url_type, $ip) {

  //returning users, but already logged in: don't need a session to track pages.
  if($acct->uid > 0) {
		
	}	
	else { //returning users, not logged in, if session is false, create one.
		//check org id if no session variable
		if($orgid == 0) {
			$orgid = _nnels_stats_get_org_by_referring_url($ref);
		}

		$arr = array(
		  'referrer' => $ref,
		  'new_user' => 0, //0=returning user, 1=new ... override this in hook_user_insert
		  'referring_url_type' => $referring_url_type,
		  'orgid' => $orgid,
		  'pages' => array(),
		  'authen_result' => 0,
		  //'authen_success' => 0,
		  //'authen_failure_reason' => 0,
		  'ip_address' => $ip,
		);
		$arr['visitid'] = _nnels_add_visit($arr);
		//start the session w/ a new visitid
		$_SESSION['nnels_stats'] = $arr;


  }

}

/**
 * populates db
 *
 * @param array $arr
 *
 * @return integer $visitid
 *  the primary key from the db insert
 *   
 */
function _nnels_add_visit($arr) {
	//printAndDie(__FUNCTION__, $arr);
	$visitid = db_insert('nnels_stats')
	  ->fields(array(
	    'new_user' => $arr['new_user'],
	    'authen_result' => $arr['authen_result'],
	    //'authen_success' => $arr['authen_success'],
	    //'authen_failure_reason' => $arr['authen_failure_reason'],
	    'orgid' => $arr['orgid'],
	    'referring_url_type' => $arr['referring_url_type'],
	    'created' => REQUEST_TIME,
	    'ip_address' => $arr['ip_address'],
	  ))
	  ->execute();
	//dpm($arr);  
  return $visitid;
 
}

/**
 * updates visit row with authentication result
 *
 * @param array $arr
 * @param integer $success
 *  1 = successful login, 0 = failure
 * @param array $reason
 *  0 = no reason (or successful login), 1 = 
 *
 *   
 */
function _nnels_update_visit($arr, $success, $reason, $uid) {
	if(!empty($arr['visitid']) ) {
		
		if($arr['orgid'] == 0) $arr['orgid'] = nnels_stats_get_org_by_uid($uid);
		
		//$result = ($success == 1)? $result = 0 : $result = $reason;
		$result = $reason + 1;
		
		$num_updated = db_update('nnels_stats') 
		  ->fields(array(
		  	'new_user' => $arr['new_user'], //0=returning; 1 = new
		    'authen_result' => $result,
		    'orgid' => $arr['orgid'],
		    //'referring_url_type' => $arr['referring_url_type'],
		    'created' => REQUEST_TIME,
    		//'ip_address' => $arr['ip_address'],
		  ))
		  ->condition('visitid', $arr['visitid'], '=')
		  ->execute();
	}
 
}

/**
 * Get referring URL type.
 *
 * @param string $url
 *   the referring url
 * @return
 *   integer - the url type: 1 = blank / direct; 2 = external (not partner); 3 = referring (partner); 4 = site?
 */
function nnels_stats_get_url_type($url) {
	global $user;
	
	//if(!empty($url) && $user->uid > 0) return 2;
	
	
  $type = 1;
  $pos = strpos($url, "cals_dev");
  $pos = strpos($url, "nnels.ca");
  
  //printAndDie($pos, $url);
  if($pos !== FALSE) {
    return 4; //ignore this, don't create a session
  }
  
  if(empty($url)) {
    return 1; //
  }
  
  $orgid = _nnels_stats_get_org_by_referring_url($url);
  if($orgid == 0) {
    return 2;
  }
  else {
    return 3;  
  }
  
  
  //if($)
  
  
  return 4; //site
}

/**
 * Get user agent.
 *
 * @return
 *   string user agent, or empty string if user agent does not exist
 */
function nnels_stats_get_user_agent() {
  return isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
}

/**
 * Get user agent.
 *
 * @return
 *   string referring URL
 */
function nnels_stats_get_referrer() {
  return isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
}

/**
 * Get org by referring URL.
 *
 * @return integer - the library node id
 */
function _nnels_stats_get_org_by_referring_url($referring_url) {

	$target = db_query("SELECT a.setting_name, a.setting_value 
    FROM {calsauthentargets} a LEFT JOIN {calsauthentargets} b ON a.nid = b.nid 
    WHERE b.setting_name = 'referring_url' AND :referring_url_value
    REGEXP b.setting_value",
    array(':referring_url_value' => $referring_url)
  );
  if ($target->rowCount()) {
    foreach ($target as $attr) {
			//dpm($attr);

      // The node ID of the organization that corresponds to the registered
      // referring URL.
      if ($attr->setting_name == 'node') {
      	return $attr->setting_value;
      }
    }
  }
	//dpm("THERE SEEMS TO BE NO ASSOCIATED URL???");

	return 0;

}

/**
 * Get organization NID from $uid.
 *
 * @return
 *   integer node id
 */
function nnels_stats_get_org_by_uid($uid) {
 
  $account = user_load($uid);
  if(!empty($account->field_organization))  {
    return $account->field_organization['und'][0]['nid'];
  }
 
  $nid = db_query(
  	"select field_organization_nid 
  		from {field_data_field_organization} 
  		where entity_id = :uid and entity_type = :type ", 
    	array(":uid" => $uid, ":type" => "user") 
  )->fetchField();
  if(!$nid) $nid = 0; 
  return $nid;  
}


/**
 * Implements hook_entity_info().
 */
function nnels_stats_entity_info() {

  $info = array();

  $info['nnelsvisitor'] = array(
    'label' => t('Visit'),
    'base table' => 'nnels_stats',
    'entity keys' => array(
      'id' => 'visitid',
    ),
    'module' => 'nnels_stats',
    'views controller class' => 'EntityDefaultViewsController',
    
  );

  return $info;
}
/**
 * Simple test ....
 */
function nnels_stats_test_entity() {

	try{
		$type = 'nnelsvisitor';
		$wrapper = entity_metadata_wrapper('nnelsvisitor', 1071);
		
		dpm($wrapper);
		$visits = entity_load('nnelsvisitor', array(1071, 1070));
		dpm($visits);
		$info = entity_get_info($type);
		dpm($info);
		$info = entity_get_info("node");
		dpm($info);
		
		
	}
	catch(Exception $e) {
	
	  dpm($e);
	
	}
	return 'Some string';

}


   

/**
 * Returns information about the default search module.
 *
 * @return
 *    The search_get_info() array element for the default search module, if any.
 */
function nnels_stats_get_default_module_info() {
  $info = nnels_stats_get_info();
  $default = variable_get('nnels_stats_default_module', 'node');
  if (isset($info[$default])) {
    return $info[$default];
  }
  // The variable setting does not match any active module, so just return
  // the info for the first active module (if any).
  return reset($info);
}
